on:
  push:
    branches:
      - main
jobs:
  prettier-and-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run format:check
      - name: Run ESLint
        run: npm run lint
